const $=id=>document.getElementById(id);const canvas=$("chart"),ctx=canvas.getContext("2d");let ws=null, candles=[], current=null, algo=true, balance=10000, position=null, trades=JSON.parse(localStorage.getItem("jk_algo_trades")||"[]"), realized=Number(localStorage.getItem("jk_algo_pnl")||0);const FAST=9,SLOW=26,SL=.01,TP=.01,RISK=.005,FEE=.0005;
function save(){localStorage.setItem("jk_algo_trades",JSON.stringify(trades.slice(-100)));localStorage.setItem("jk_algo_pnl",realized)}
function fmt(n){return "$"+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function ema(a,p){let k=2/(p+1),v=a[0];return a.map((x,i)=>i?(v=x*k+v*(1-k),v):v)}
function connect(){if(ws)ws.close();candles=[];setStatus(false);const sym=$("symbol").value,tf=$("timeframe").value;$("pair").textContent=sym;ws=new WebSocket("wss://public-socket.india.delta.exchange");ws.onopen=()=>{setStatus(true);ws.send(JSON.stringify({type:"subscribe",payload:{channels:[{name:"candlestick_"+tf,symbols:[sym]}]}}))};ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type!=="candlestick_"+tf)return;const c={t:Number(m.ts),o:+m.o,h:+m.h,l:+m.l,c:+m.c,v:+(m.v||0)};const last=candles[candles.length-1];if(last&&last.t===c.t)candles[candles.length-1]=c;else candles.push(c);candles=candles.slice(-120);current=c;onCandle(c);draw()}catch(_){}};ws.onerror=()=>setStatus(false);ws.onclose=()=>{setStatus(false);setTimeout(()=>{if(ws===null||ws.readyState===WebSocket.CLOSED)connect()},2500)}}
function setStatus(live){$("dot").classList.toggle("live",live);$("connection").textContent=live?"LIVE MARKET":"Reconnecting…"}
function onCandle(c){$("price").textContent=fmt(c.c);if(position){const p=(c.c-position.entry)*(position.side==="BUY"?1:-1)*position.qty;$("equity").textContent=fmt(balance+p);if((position.side==="BUY"&&c.c<=position.sl)||(position.side==="BUY"&&c.c>=position.tp)||(position.side==="SELL"&&c.c>=position.sl)||(position.side==="SELL"&&c.c<=position.tp))closePosition(c.c,(position.side==="BUY"?(c.c<=position.sl?"STOP":"TARGET"):(c.c>=position.sl?"STOP":"TARGET")));}if(!algo||position||candles.length<SLOW+2)return;const a=candles.map(x=>x.c),f=ema(a,FAST),s=ema(a,SLOW),prevF=f[f.length-2],prevS=s[s.length-2],nowF=f.at(-1),nowS=s.at(-1);let side=null;if(prevF<=prevS&&nowF>nowS)side="BUY";if(prevF>=prevS&&nowF<nowS)side="SELL";if(side){$("signal").textContent=side+" SIGNAL";openPosition(side,c.c)}}
function openPosition(side,price){const qty=(balance*RISK)/(price*SL);const fee=qty*price*FEE;if(qty<=0||fee>balance)return;const sl=side==="BUY"?price*(1-SL):price*(1+SL),tp=side==="BUY"?price*(1+TP):price*(1-TP);balance-=fee;position={side,qty,entry:price,sl,tp,fee};$("signal").textContent=side+" • PAPER";render()}
function closePosition(price,reason){if(!position)return;const p=position,pnl=(price-p.entry)*p.qty*(p.side==="BUY"?1:-1)-price*p.qty*FEE;balance+=pnl;realized+=pnl;trades.push({time:new Date().toLocaleTimeString(),side:p.side,qty:p.qty,price, pnl,reason});position=null;save();render()}
function render(){$("balance").textContent=fmt(balance);$("pnl").textContent=fmt(realized);$("pnl").className=realized>=0?"buy":"sell";$("position").textContent=position?position.side:"NONE";if(position){$("empty").classList.add("hidden");$("pos").classList.remove("hidden");$("pos").innerHTML=[["Side",position.side],["Qty",position.qty.toFixed(6)],["Entry",fmt(position.entry)],["SL / TP",fmt(position.sl)+" / "+fmt(position.tp)]].map(x=>"<div><span>"+x[0]+"</span><b>"+x[1]+"</b></div>").join("")}else{$("empty").classList.remove("hidden");$("pos").classList.add("hidden");$("equity").textContent=fmt(balance)}$("history").innerHTML=trades.slice(-20).reverse().map(t=>"<tr><td>"+t.time+"</td><td class='"+t.side.toLowerCase()+"'>"+t.side+"</td><td>"+t.qty.toFixed(6)+"</td><td>"+fmt(t.price)+"</td><td class='"+(t.pnl>=0?"buy":"sell")+"'>"+fmt(t.pnl)+"</td><td>"+t.reason+"</td></tr>").join("")}
function draw(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);if(candles.length<2)return;const min=Math.min(...candles.map(x=>x.l)),max=Math.max(...candles.map(x=>x.h)),pad=18,dx=(w-pad*2)/(candles.length-1),y=v=>h-pad-(v-min)/(max-min||1)*(h-pad*2);ctx.strokeStyle="#1c2632";ctx.lineWidth=1;for(let i=0;i<5;i++){let yy=pad+i*(h-pad*2)/4;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}candles.forEach((c,i)=>{let x=pad+i*dx;ctx.strokeStyle=c.c>=c.o?"#4ed9a5":"#ff7180";ctx.beginPath();ctx.moveTo(x,y(c.h));ctx.lineTo(x,y(c.l));ctx.stroke();ctx.fillStyle=ctx.strokeStyle;let top=y(Math.max(c.o,c.c)),bh=Math.max(2,Math.abs(y(c.o)-y(c.c)));ctx.fillRect(x-2,top,4,bh)});const f=ema(candles.map(x=>x.c),FAST),s=ema(candles.map(x=>x.c),SLOW);[[f,"#f5a623"],[s,"#4c9cff"]].forEach(([a,col])=>{ctx.strokeStyle=col;ctx.lineWidth=1.5;ctx.beginPath();a.forEach((v,i)=>{const x=pad+i*dx;if(i)ctx.lineTo(x,y(v));else ctx.moveTo(x,y(v))});ctx.stroke()})}
$("algo").onclick=()=>{algo=!algo;$("algo").textContent=algo?"ALGO ON":"ALGO OFF";$("algo").classList.toggle("off",!algo)};$("symbol").onchange=connect;$("timeframe").onchange=connect;$("reset").onclick=()=>{if(confirm("Reset paper account to $10,000?")){balance=10000;position=null;realized=0;trades=[];save();render()}};window.addEventListener("resize",draw);render();connect();