const $=id=>document.getElementById(id);
const KEY='jk_algo_hub_v2';
const DEFAULT={mode:'paper',virtualCapital:10000,balance:10000,realized:0,positions:[],pending:[],closed:[],lastPage:'watchlist',lastSymbol:'BTCUSD',lastTf:'5m',layout:1,algoOn:false,algoCapital:10000,algoSymbol:'BTCUSD',algoTf:'5m',strategy:'EMA 9 / 26',watch:['BTCUSD','ETHUSD','SOLUSD','GOLD','SILVER','OIL','NIFTY','BANKNIFTY','FINNIFTY','NIFTY MIDCAP'],chartPanels:[{symbol:'BTCUSD',tf:'5m',ind:{ema9:true,ema26:true,rsi:false,macd:false,boll:false,vwap:false,volume:true},bg:'#0b1118',bull:'#32d39d',bear:'#ff6874',tz:'Asia/Kolkata',drawings:[],sl:null,tp:null},{symbol:'ETHUSD',tf:'5m',ind:{ema9:true,ema26:true,rsi:false,macd:false,boll:false,vwap:false,volume:true},bg:'#0b1118',bull:'#32d39d',bear:'#ff6874',tz:'Asia/Kolkata',drawings:[],sl:null,tp:null}],scripts:[],api:{broker:'Custom REST / WebSocket',key:'',secret:'',token:''}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
state.chartPanels=(state.chartPanels&&state.chartPanels.length?state.chartPanels:DEFAULT.chartPanels).map((x,i)=>Object.assign({},DEFAULT.chartPanels[i%2],x));
state.positions=state.positions||[];state.pending=state.pending||[];state.closed=state.closed||[];state.watch=state.watch||DEFAULT.watch;state.api=Object.assign({},DEFAULT.api,state.api||{});
const validLayouts=[1,2,4,6,8];
if(!state.layoutInitialized){state.layout=1;state.layoutInitialized=true}
if(!validLayouts.includes(Number(state.layout)))state.layout=1;
let page=state.lastPage||'watchlist',activeTab='positions',layout=Number(state.layout)||1,feed={};
const cryptoMap={BTCUSD:'BTCUSDT',ETHUSD:'ETHUSDT',SOLUSD:'SOLUSDT'};
const names={BTCUSD:'Bitcoin',ETHUSD:'Ethereum',SOLUSD:'Solana',GOLD:'Gold',SILVER:'Silver',OIL:'Crude Oil',NIFTY:'Nifty 50',BANKNIFTY:'Bank Nifty',FINNIFTY:'Fin Nifty','NIFTY MIDCAP':'Nifty Midcap 100'};
const base={BTCUSD:68000,ETHUSD:3200,SOLUSD:150,GOLD:3350,SILVER:39,OIL:68,NIFTY:25000,BANKNIFTY:55000,FINNIFTY:26000,'NIFTY MIDCAP':58000};
const tfs=['1m','3m','5m','15m','30m','1H','2H','4H','1D','1W','1M'];
const $store=()=>localStorage.setItem(KEY,JSON.stringify(state));
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function num(n){return Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:4})}
function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function setConn(live,text){$('connDot').classList.toggle('live',live);$('connText').textContent=text}
function pageShow(p){page=p;state.lastPage=p;$store();document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('page-'+p).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));if(p==='watchlist')renderWatch();if(p==='charts')renderCharts();if(p==='algo')renderAlgo();if(p==='pnl')renderPnl()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>pageShow(b.dataset.page));
$('modeBtn').onclick=()=>chooseMode();
function chooseMode(){modal('Trading Mode', '<div class="option" data-mode="paper"><b>PAPER TRADING</b><span>Virtual money</span></div><div class="option" data-mode="real"><b>REAL TRADING</b><span>Broker account</span></div>');document.querySelectorAll('[data-mode]').forEach(e=>e.onclick=()=>{if(e.dataset.mode==='real'&&!state.api.token&&!state.api.key){toast('Connect a broker/API before Real Trading');return}if(e.dataset.mode==='real'&&!confirm('REAL TRADING uses real money and actual broker orders. Continue?'))return;state.mode=e.dataset.mode;$store();closeModal();syncHeader();renderAll()})}
function syncHeader(){$('modeBtn').textContent=state.mode==='paper'?'PAPER':'REAL';$('subtitle').textContent=state.mode==='paper'?'Paper Trading • Live Market':'Real Trading • Broker';$('accountMode').textContent=state.mode==='paper'?'Paper account':'Real broker account';}
function renderWatch(){const root=$('watchlist');root.innerHTML=state.watch.map(s=>{const q=quote(s),ch=q.change;return '<div class="watch-card" data-sym="'+s+'"><div class="watch-top"><div><div class="watch-symbol">'+s+'</div><span class="watch-name">'+(names[s]||s)+'</span></div><div class="watch-price">'+money(q.price)+'</div></div><div class="watch-bottom"><span class="watch-name">'+q.source+'</span><span class="watch-change '+(ch>=0?'up':'down')+'">'+(ch>=0?'+':'')+ch.toFixed(2)+'%</span></div></div>'}).join('');root.querySelectorAll('.watch-card').forEach(e=>e.onclick=()=>{openSymbol(e.dataset.sym);pageShow('charts')})}
function quote(s){const f=feed[s];if(f&&f.price)return{price:f.price,change:f.change||0,source:'LIVE'};let seed=0;for(const c of s)seed+=c.charCodeAt(0);const drift=Math.sin(Date.now()/90000+seed)*.008;return{price:base[s]*(1+drift),change:drift*100,source:cryptoMap[s]?'LIVE loading':'Provider required'}}
async function fetchCandles(sym,tf){if(!cryptoMap[sym])return synthetic(sym,tf);const interval=({'1m':'1m','3m':'3m','5m':'5m','15m':'15m','30m':'30m','1H':'1h','2H':'2h','4H':'4h','1D':'1d','1W':'1w','1M':'1M'})[tf]||'5m';try{const u='https://api.binance.com/api/v3/klines?symbol='+cryptoMap[sym]+'&interval='+interval+'&limit=180';const r=await fetch(u);if(!r.ok)throw Error('market');const a=await r.json();return a.map(x=>({t:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]}))}catch(e){return synthetic(sym,tf)}}
function synthetic(sym,tf){let arr=[],p=base[sym]||100,seed=0;for(const c of sym)seed+=c.charCodeAt(0);let step=({'1m':60000,'3m':180000,'5m':300000,'15m':900000,'30m':1800000,'1H':3600000,'2H':7200000,'4H':14400000,'1D':86400000,'1W':604800000,'1M':2592000000})[tf]||300000,now=Date.now()-step*179;for(let i=0;i<180;i++){const wave=Math.sin((i+seed)*.21)*.012+Math.sin((i+seed)*.061)*.018;let o=p*(1+wave*.2),c=p*(1+wave);let h=Math.max(o,c)*(1+.004+Math.abs(Math.sin(i+seed))*.003),l=Math.min(o,c)*(1-.004-Math.abs(Math.cos(i+seed))*.003);arr.push({t:now+i*step,o,h,l,c,v:Math.abs(c-o)*1000});p=c}return arr}
function ema(a,p){if(!a.length)return[];let k=2/(p+1),v=a[0];return a.map((x,i)=>i?(v=x*k+v*(1-k),v):v)}
function sma(a,p){return a.map((_,i)=>{const z=a.slice(Math.max(0,i-p+1),i+1);return z.reduce((x,y)=>x+y,0)/z.length})}
function rsi(a,p=14){let out=[],g=0,l=0;for(let i=0;i<a.length;i++){if(i){let d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}out.push(l?100-100/(1+g/l):50)}return out}
function boll(a,p=20,m=2){return a.map((_,i)=>{const z=a.slice(Math.max(0,i-p+1),i+1),m0=z.reduce((x,y)=>x+y,0)/z.length,sd=Math.sqrt(z.reduce((x,y)=>x+(y-m0)**2,0)/z.length);return{mid:m0,up:m0+m*sd,lo:m0-m*sd}})}
function openSymbol(s){state.lastSymbol=s;state.chartPanels[0].symbol=s;$store();renderCharts()}
function renderCharts(){const panelCount=layout===1?1:layout;const root=$('chartWorkspace');root.className='chart-workspace '+(layout>1?'layout-'+layout:'');root.innerHTML='';for(let i=0;i<panelCount;i++){if(!state.chartPanels[i])state.chartPanels[i]=Object.assign({},state.chartPanels[0],{symbol:i?state.watch[i%state.watch.length]:state.lastSymbol});const p=state.chartPanels[i];if(p.zoom==null)p.zoom=1;const el=document.createElement('div');el.className='chart-panel';el.innerHTML='<div class="chart-overlay"><b>'+p.symbol+'</b><span>'+p.tf+'</span></div><canvas></canvas>';root.appendChild(el);drawPanel(el,p,i)}
$('chartSymbol').textContent=state.chartPanels[0].symbol+' ▾';const q=quote(state.chartPanels[0].symbol);$('chartPrice').textContent=money(q.price);$('chartChange').textContent=(q.change>=0?'+':'')+q.change.toFixed(2)+'%';$('chartChange').className='price-change '+(q.change>=0?'up':'down');$('timeframes').innerHTML=tfs.map(x=>'<button class="tf '+(x===state.chartPanels[0].tf?'active':'')+'" data-tf="'+x+'">'+x+'</button>').join('');$('timeframes').querySelectorAll('.tf').forEach(b=>b.onclick=()=>setTf(b.dataset.tf));$store()}
async function drawPanel(el,p,idx){const c=el.querySelector('canvas'),ctx=c.getContext('2d');if(!ctx)return;const drawToken=Date.now()+Math.random();c.dataset.drawToken=drawToken;const rect=el.getBoundingClientRect(),d=devicePixelRatio||1;c.width=rect.width*d;c.height=Math.max(300,rect.height)*d;ctx.setTransform(d,0,0,d,0,0);const w=rect.width,h=Math.max(300,rect.height);let data;try{data=await fetchCandles(p.symbol,p.tf)}catch(e){data=synthetic(p.symbol,p.tf)}if(c.dataset.drawToken!=drawToken)return;if(!Array.isArray(data)||data.length<2)data=synthetic(p.symbol,p.tf);if(idx===0){const last=data.at(-1);if(last){feed[p.symbol]={price:last.c,change:((last.c-data[Math.max(0,data.length-2)].c)/data[Math.max(0,data.length-2)].c)*100}}}ctx.fillStyle=p.bg||'#0b1118';ctx.fillRect(0,0,w,h);const visible=Math.max(30,Math.min(data.length,Math.round(data.length/(p.zoom||1)))),start=Math.max(0,data.length-visible),view=data.slice(start),pad={l:8,r:48,t:28,b:22},vals=view.flatMap(x=>[x.h,x.l]),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,pw=w-pad.l-pad.r,ph=h-pad.t-pad.b,step=pw/view.length,body=Math.max(2,step*.62),x=i=>pad.l+i*step+step/2,y=v=>pad.t+(max-v)/range*ph;ctx.strokeStyle='#182431';ctx.lineWidth=1;for(let i=0;i<5;i++){let yy=pad.t+i*ph/4;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillStyle='#59687a';ctx.font='10px system-ui';ctx.fillText(money(max-(max-min)*i/4),w-pad.r+5,yy+3)}view.forEach((z,i)=>{const up=z.c>=z.o;ctx.strokeStyle=up?p.bull:p.bear;ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x(i),y(z.h));ctx.lineTo(x(i),y(z.l));ctx.stroke();ctx.fillRect(x(i)-body/2,y(Math.max(z.o,z.c)),body,Math.max(1,Math.abs(y(z.o)-y(z.c))))});const closes=view.map(z=>z.c);function line(a,col){ctx.strokeStyle=col;ctx.lineWidth=1.3;ctx.beginPath();a.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke()}if(p.ind.ema9)line(ema(closes,9),'#f3b45b');if(p.ind.ema26)line(ema(closes,26),'#6da7ff');if(p.ind.boll){const b=boll(closes);line(b.map(z=>z.up),'#8b78d9');line(b.map(z=>z.lo),'#8b78d9')}if(p.ind.vwap){let pv=0,vol=0;line(view.map(z=>(pv+=z.c*z.v,vol+=z.v,pv/vol)),'#d889d9')}const pos=state.positions.find(z=>z.symbol===p.symbol&&z.mode===state.mode);
c.onwheel=e=>{e.preventDefault();p.zoom=Math.max(1,Math.min(8,(p.zoom||1)*(e.deltaY<0?1.18:.847458)));$store();drawPanel(el,p,idx)};
let touchStartDist=0,touchStartZoom=p.zoom||1;
c.addEventListener('touchstart',e=>{if(e.touches.length===2){e.preventDefault();const x=e.touches[0],y=e.touches[1];touchStartDist=Math.hypot(x.clientX-y.clientX,x.clientY-y.clientY);touchStartZoom=p.zoom||1}},{passive:false});
c.addEventListener('touchmove',e=>{if(e.touches.length===2&&touchStartDist>0){e.preventDefault();const x=e.touches[0],y=e.touches[1],dist=Math.hypot(x.clientX-y.clientX,x.clientY-y.clientY);p.zoom=Math.max(1,Math.min(8,touchStartZoom*dist/touchStartDist));drawPanel(el,p,idx)}},{passive:false});
c.addEventListener('touchend',e=>{if(e.touches.length<2){touchStartDist=0;$store()}},{passive:false});
el.querySelectorAll('.trade-line,.trade-label,.chart-order-panel').forEach(x=>x.remove());if(pos){addTradeLine(el,'sl',pos.sl,p,min,max,ph,pad,range);addTradeLine(el,'tp',pos.tp,p,min,max,ph,pad,range);const box=document.createElement('div');box.className='chart-order-panel';box.innerHTML='<button class="mini-action">CLOSE</button>';box.querySelector('button').onclick=()=>closePosition(pos.id,'Manual close');el.appendChild(box)}}
function addTradeLine(el,type,price,p,min,max,ph,pad,range){const top=pad.t+(max-price)/range*ph;const line=document.createElement('div');line.className='trade-line '+(type==='sl'?'sl-line':'tp-line');line.style.top=top+'px';const lab=document.createElement('div');lab.className='trade-label '+(type==='sl'?'sl-label':'tp-label');lab.style.top=(top-8)+'px';lab.textContent=type.toUpperCase()+' '+num(price);el.appendChild(line);el.appendChild(lab);line.style.pointerEvents='auto';line.style.cursor='ns-resize';let drag=false;line.onpointerdown=e=>{drag=true;line.setPointerCapture(e.pointerId)};line.onpointermove=e=>{if(!drag)return;const r=el.getBoundingClientRect();const y=Math.max(pad.t,Math.min(r.height-pad.b,e.clientY-r.top));const np=max-(y-pad.t)/ph*range;const pos=state.positions.find(z=>z.symbol===p.symbol&&z.mode===state.mode);if(pos){if(type==='sl')pos.sl=np;else pos.tp=np;lab.textContent=type.toUpperCase()+' '+num(np);state.chartPanels[0][type]=np;updatePnlOnly()}};line.onpointerup=()=>{if(drag){drag=false;$store();toast(type.toUpperCase()+' updated')}}}
function setTf(tf){state.lastTf=tf;state.chartPanels[0].tf=tf;$store();renderCharts();startMarket()}
$('chartSymbol').onclick=()=>chooseSymbol(0);
function chooseSymbol(idx){modal('Select Symbol',state.watch.map(s=>'<div class="option" data-s="'+s+'"><b>'+s+'</b><span>'+names[s]+'</span></div>').join(''));document.querySelectorAll('[data-s]').forEach(e=>e.onclick=()=>{state.chartPanels[idx].symbol=e.dataset.s;if(idx===0)state.lastSymbol=e.dataset.s;$store();closeModal();renderCharts();startMarket()})}
$('layoutBtn').onclick=()=>{const n=layout===1?2:layout===2?4:layout===4?6:layout===6?8:1;layout=n;state.layout=n;state.layoutInitialized=true;$store();renderCharts()}
$('toolsBtn').onclick=()=>modal('Chart Tools','<div class="draw-tool"><button data-tool="horizontal">Horizontal</button><button data-tool="vertical">Vertical</button><button data-tool="trend">Trend Line</button><button data-tool="ray">Ray</button><button data-tool="rect">Rectangle</button><button data-tool="cross">Crosshair</button></div><p class="hint">Drawing objects are stored per chart panel.</p>');document.addEventListener('click',function toolOnce(e){if(!e.target.dataset.tool)return;const tool=e.target.dataset.tool;state.chartPanels[0].drawings.push({type:tool,created:Date.now()});$store();closeModal();toast(tool+' tool selected')},{once:false});
$('indBtn').onclick=()=>{const p=state.chartPanels[0];modal('Indicators','<div class="setting-row"><label>EMA 9</label><input type="checkbox" data-ind="ema9" '+(p.ind.ema9?'checked':'')+'></div><div class="setting-row"><label>EMA 26</label><input type="checkbox" data-ind="ema26" '+(p.ind.ema26?'checked':'')+'></div><div class="setting-row"><label>RSI</label><input type="checkbox" data-ind="rsi" '+(p.ind.rsi?'checked':'')+'></div><div class="setting-row"><label>MACD</label><input type="checkbox" data-ind="macd" '+(p.ind.macd?'checked':'')+'></div><div class="setting-row"><label>Bollinger Bands</label><input type="checkbox" data-ind="boll" '+(p.ind.boll?'checked':'')+'></div><div class="setting-row"><label>VWAP</label><input type="checkbox" data-ind="vwap" '+(p.ind.vwap?'checked':'')+'></div><div class="setting-row"><label>Volume</label><input type="checkbox" data-ind="volume" '+(p.ind.volume?'checked':'')+'></div>');document.querySelectorAll('[data-ind]').forEach(e=>e.onchange=()=>{p.ind[e.dataset.ind]=e.checked;$store();renderCharts()})}
$('settingsBtn').onclick=()=>chartSettings();
function chartSettings(){const p=state.chartPanels[0];modal('Chart Settings','<div class="setting-row"><label>Bull candle</label><input type="color" id="bullColor" value="'+p.bull+'"></div><div class="setting-row"><label>Bear candle</label><input type="color" id="bearColor" value="'+p.bear+'"></div><div class="setting-row"><label>Background</label><input type="color" id="bgColor" value="'+p.bg+'"></div><div class="setting-row"><label>Timezone</label><select id="tz"><option value="Asia/Kolkata">India / IST</option><option value="America/New_York">USA / New York</option><option value="Europe/London">UK / London</option><option value="Asia/Dubai">UAE / Dubai</option><option value="Asia/Singapore">Singapore</option></select></div><button class="primary full" id="pineBtn">Custom Pine Script</button>');$('tz').value=p.tz||'Asia/Kolkata';['bullColor','bearColor','bgColor'].forEach(id=>$(id).onchange=()=>{p.bull=$('bullColor').value;p.bear=$('bearColor').value;p.bg=$('bgColor').value;$store();renderCharts()});$('tz').onchange=()=>{p.tz=$('tz').value;$store();toast('Timezone saved')};$('pineBtn').onclick=()=>pineModal()}
function pineModal(){modal('Custom Pine Script','<textarea id="pineCode" style="width:100%;min-height:220px;background:#080d13;color:#dce5ee;border:1px solid #2a3848;border-radius:9px;padding:12px;font:12px monospace" placeholder="// Paste Pine Script here"></textarea><input id="pineName" placeholder="Script name" style="margin-top:8px"><button class="primary full" id="savePine">Save Script</button><div id="savedScripts" class="hint"></div>');$('savedScripts').textContent=state.scripts.length?'Saved: '+state.scripts.map(x=>x.name).join(', '):'No saved scripts';$('savePine').onclick=()=>{const code=$('pineCode').value.trim(),name=$('pineName').value.trim()||'Custom Script';if(!code)return toast('Enter Pine Script');state.scripts.push({name,code,created:Date.now()});$store();toast('Script saved locally');closeModal()}}
$('algoToggle').onchange=()=>{state.algoOn=$('algoToggle').checked;$store();renderAlgo();toast(state.algoOn?'Algo enabled':'Algo disabled')};
$('modeSelect').onclick=()=>chooseMode();
$('algoSymbol').onclick=()=>chooseAlgoSymbol();
function chooseAlgoSymbol(){modal('Algo Symbol',state.watch.map(s=>'<div class="option" data-as="'+s+'"><b>'+s+'</b></div>').join(''));document.querySelectorAll('[data-as]').forEach(e=>e.onclick=()=>{state.algoSymbol=e.dataset.as;$store();closeModal();renderAlgo()})}
$('algoTf').onclick=()=>modal('Algo Timeframe',tfs.map(x=>'<div class="option" data-at="'+x+'"><b>'+x+'</b></div>').join(''));document.addEventListener('click',e=>{if(e.target.dataset.at){state.algoTf=e.target.dataset.at;$store();closeModal();renderAlgo()}});
$('algoStrategy').onclick=()=>modal('Strategy','<div class="option" data-st="EMA 9 / 26"><b>EMA 9 / 26</b><span>Default crossover</span></div><div class="option" data-st="CUSTOM"><b>Custom Strategy</b><span>Saved Pine scripts</span></div>');document.addEventListener('click',e=>{if(e.target.dataset.st){state.strategy=e.target.dataset.st;$store();closeModal();renderAlgo()}});
$('algoCapital').onchange=()=>{state.algoCapital=Math.max(1,+$('algoCapital').value||10000);$store()};
$('customStrategy').onclick=()=>pineModal();
function renderAlgo(){$('algoToggle').checked=!!state.algoOn;$('algoCapital').value=state.algoCapital;$('algoSymbol').textContent=state.algoSymbol+' ▾';$('algoTf').textContent=state.algoTf+' ▾';$('algoStrategy').textContent=state.strategy+' ▾';$('strategyName').textContent=state.strategy==='CUSTOM'?'Custom saved strategy':'EMA 9 / 26 crossover';$('algoStatus').textContent=state.algoOn?'ON':'OFF';$('algoStatus').classList.toggle('muted',!state.algoOn);$('algoMode').textContent=state.mode==='paper'?'PAPER TRADING':'REAL TRADING';$('apiStatus').textContent=state.api.key||state.api.token?'CONFIGURED':'NOT CONNECTED';$('broker').value=state.api.broker;$('apiKey').value=state.api.key;$('apiSecret').value=state.api.secret;$('accessToken').value=state.api.token;const logs=state.closed.slice(-8).reverse();$('algoLog').innerHTML=logs.length?logs.map(x=>'<div class="log-item"><span>'+x.side+' '+x.symbol+' • '+new Date(x.entryTime).toLocaleTimeString()+'</span><b class="'+(x.pnl>=0?'up':'down')+'">'+money(x.pnl)+'</b></div>').join(''):'<div class="empty">Algo is ready. Turn it ON to allow new paper trades.</div>'}
$('testApi').onclick=()=>{state.api={broker:$('broker').value,key:$('apiKey').value,secret:$('apiSecret').value,token:$('accessToken').value};$store();$('apiStatus').textContent=state.api.key||state.api.token?'CONFIGURED':'NOT CONNECTED';toast(state.api.key||state.api.token?'Credentials saved. Broker adapter ready.':'Enter API credentials')};
function renderPnl(){updatePnlOnly();const root=$('pnlList');let arr=activeTab==='positions'?state.positions.filter(x=>x.mode===state.mode):activeTab==='pending'?state.pending.filter(x=>x.mode===state.mode):state.closed.filter(x=>x.mode===state.mode);if(!arr.length){root.innerHTML='<div class="card"><div class="empty">No '+(activeTab==='positions'?'position':activeTab==='pending'?'pending order':'closed trade')+'.</div>'+(activeTab==='positions'?'<button class="primary full" id="manualOpen">Open position</button>':'')+'</div>';if($('manualOpen'))$('manualOpen').onclick=()=>manualOpen();return}root.innerHTML=arr.slice().reverse().map(x=>tradeCard(x)).join('');root.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closePosition(b.dataset.close,'Manual close'));root.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancelPending(b.dataset.cancel));root.querySelectorAll('[data-modify]').forEach(b=>b.onclick=()=>modifyPending(b.dataset.modify))}
function tradeCard(x){const open=activeTab==='positions',side=x.side||'BUY';return '<div class="trade-card"><div class="trade-main"><div><b class="'+(side==='BUY'?'up':'down')+'">'+side+' '+x.symbol+'</b><div class="watch-name">'+(x.strategy||'Manual')+' • '+(open?'OPEN':activeTab==='pending'?'PENDING':'CLOSED')+'</div></div><b class="'+((open?unreal(x):x.pnl)>=0?'up':'down')+'">'+money(open?unreal(x):x.pnl)+'</b></div><div class="trade-meta"><div><span>Qty</span><b>'+num(x.qty)+'</b></div><div><span>Entry</span><b>'+money(x.entry||x.price)+'</b></div><div><span>SL</span><b>'+money(x.sl||0)+'</b></div><div><span>TP</span><b>'+money(x.tp||0)+'</b></div></div><div class="trade-actions">'+(open?'<button class="danger" data-close="'+x.id+'">CLOSE</button>':activeTab==='pending'?'<button class="small-btn" data-modify="'+x.id+'">MODIFY</button><button class="danger" data-cancel="'+x.id+'">CANCEL</button>':'')+'</div></div>'}
function unreal(x){const q=quote(x.symbol).price;return(q-x.entry)*x.qty*(x.side==='BUY'?1:-1)}
function updatePnlOnly(){let ps=state.positions.filter(x=>x.mode===state.mode),u=ps.reduce((a,x)=>a+unreal(x),0),real=state.closed.filter(x=>x.mode===state.mode).reduce((a,x)=>a+(x.pnl||0),0),bal=state.mode==='paper'?state.balance:0;$('equity').textContent=money(state.mode==='paper'?bal+u:u);$('available').textContent=money(state.mode==='paper'?bal:0);$('totalPnl').textContent=money(real+u);$('totalPnl').className=(real+u)>=0?'up':'down'}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));renderPnl()});
function manualOpen(){modal('Open Position','<label>Symbol<select id="mSym">'+state.watch.map(s=>'<option>'+s+'</option>').join('')+'</select></label><label style="display:block;margin-top:10px">Side<select id="mSide"><option>BUY</option><option>SELL</option></select></label><label style="display:block;margin-top:10px">Quantity<input id="mQty" type="number" value="1" step="any"></label><label style="display:block;margin-top:10px">Stop Loss<input id="mSl" type="number" step="any"></label><label style="display:block;margin-top:10px">Take Profit<input id="mTp" type="number" step="any"></label><button class="primary full" id="mOpenBtn">OPEN</button>');$('mOpenBtn').onclick=()=>{const s=$('mSym').value,price=quote(s).price,side=$('mSide').value,qty=+$('mQty').value||1,sl=+$('mSl').value||price*(side==='BUY'?.99:1.01),tp=+$('mTp').value||price*(side==='BUY'?1.01:.99);openPosition({symbol:s,side,qty,entry:price,sl,tp,strategy:'Manual'});closeModal()}}
function openPosition(o){const pos=Object.assign({id:crypto.randomUUID(),mode:state.mode,entryTime:Date.now()},o);if(state.mode==='paper'){const required=pos.entry*pos.qty;if(required>state.balance&&pos.symbol!=='BTCUSD'){toast('Insufficient paper balance');return}}state.positions.push(pos);$store();toast((pos.side==='BUY'?'BUY':'SELL')+' '+pos.symbol+' opened');renderAll()}
function closePosition(id,reason){const p=state.positions.find(x=>x.id===id);if(!p)return;const exit=quote(p.symbol).price,pnl=(exit-p.entry)*p.qty*(p.side==='BUY'?1:-1);state.positions=state.positions.filter(x=>x.id!==id);state.closed.push(Object.assign({},p,{exit,pnl,exitTime:Date.now(),status:'CLOSED',reason}));if(state.mode==='paper'){state.balance+=pnl} $store();toast('Position closed • '+money(pnl));renderAll()}
function cancelPending(id){state.pending=state.pending.filter(x=>x.id!==id);$store();renderPnl();toast('Pending order cancelled')}
function modifyPending(id){const p=state.pending.find(x=>x.id===id);if(!p)return;const v=prompt('New order price',p.price);if(v&&isFinite(+v)){p.price=+v;$store();renderPnl();toast('Order modified')}}
function renderAll(){syncHeader();renderWatch();renderCharts();renderAlgo();renderPnl()}
function modal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('addWatch').onclick=()=>{const s=prompt('Symbol to add (example BTCUSD, ETHUSD, NIFTY)', '');if(s){s=s.trim().toUpperCase();if(!state.watch.includes(s)){state.watch.push(s);if(!base[s])base[s]=100; $store();renderWatch()}}};
$('accountSettings').onclick=()=>{modal('Paper Account','<div class="setting-row"><label>Virtual Capital</label><input id="vcap" type="number" value="'+state.virtualCapital+'"></div><button class="primary full" id="saveCap">Save Capital</button><button class="danger-wide" id="resetPaper">RESET PAPER ACCOUNT</button><p class="hint">Reset only clears paper positions, pending orders, closed history, balance and P&L. Chart/watchlist settings remain.</p>');$('saveCap').onclick=()=>{state.virtualCapital=Math.max(1,+$('vcap').value||10000);if(state.mode==='paper'&&!state.positions.length)state.balance=state.virtualCapital;$store();closeModal();renderAll();toast('Virtual capital saved')};$('resetPaper').onclick=()=>{if(confirm('Reset paper account?')){state.positions=state.positions.filter(x=>x.mode!=='paper');state.pending=state.pending.filter(x=>x.mode!=='paper');state.closed=state.closed.filter(x=>x.mode!=='paper');state.balance=state.virtualCapital;$store();closeModal();renderAll();toast('Paper account reset')}}}; 
function startMarket(){setConn(false,'Connecting');if(window._marketTimer)clearInterval(window._marketTimer);const update=async()=>{const s=state.chartPanels[0].symbol;if(cryptoMap[s]){try{const q=await fetch('https://api.binance.com/api/v3/ticker/24hr?symbol='+cryptoMap[s]).then(r=>r.json());feed[s]={price:+q.lastPrice,change:+q.priceChangePercent};setConn(true,'LIVE MARKET')}catch(e){setConn(false,'Offline')}}else setConn(false,'Provider required');if(page==='watchlist')renderWatch();if(page==='charts')renderCharts();if(page==='pnl')renderPnl();checkStops();checkAlgo()};update();window._marketTimer=setInterval(update,5000)}
function checkStops(){for(const p of [...state.positions]){const q=quote(p.symbol).price;if((p.side==='BUY'&&q<=p.sl)||(p.side==='SELL'&&q>=p.sl))closePosition(p.id,'Stop Loss');else if((p.side==='BUY'&&q>=p.tp)||(p.side==='SELL'&&q<=p.tp))closePosition(p.id,'Take Profit')}}
let lastAlgoBar=0;
async function checkAlgo(){if(!state.algoOn||state.positions.some(x=>x.mode===state.mode&&x.symbol===state.algoSymbol))return;const d=await fetchCandles(state.algoSymbol,state.algoTf);if(d.length<30)return;const c=d.map(x=>x.c),f=ema(c,9),s=ema(c,26),i=c.length-1;if(d[i].t===lastAlgoBar)return;lastAlgoBar=d[i].t;const buy=f[i-1]<=s[i-1]&&f[i]>s[i],sell=f[i-1]>=s[i-1]&&f[i]<s[i];if(buy||sell){const side=buy?'BUY':'SELL',price=c[i],risk=state.algoCapital*.005,qty=Math.max(.0001,risk/(price*.01)),sl=side==='BUY'?price*.99:price*1.01,tp=side==='BUY'?price*1.01:price*.99;openPosition({symbol:state.algoSymbol,side,qty,entry:price,sl,tp,strategy:'EMA 9 / 26'});$('algoLast').textContent=side+' signal • '+new Date().toLocaleTimeString();toast('Algo '+side+' '+state.algoSymbol)}}
function renderPage(){pageShow(page);startMarket()}
renderPage();